base_url: "http://export.arxiv.org/api/query?"
log_dir: "/Users/blacktear/github//arxiv_auto_crawler/Log/"
link_dir: "/Users/blacktear/github/arxiv_auto_crawler/Link/"
metadata_dir: "/Users/blacktear/github/arxiv_auto_crawler/Metadata/"
pdf_dir: "/Users/blacktear/github/arxiv_auto_crawler/Pdf/"
search_query: 'cat:cs.LG'  # search for electron in all fields
total_results : 100  # want [total_results]*5 total results
wait_time: 3  # number of seconds to wait beetween calls
sortBy: 'submittedDate'
sortOrder: 'descending'
last_update_date: '2021-08-25'
log_date: '2021-08-31'